### ISSUE TITLE
Preserve resource group tags for an existing group

### ISSUE THREAD

**Issue by kitforbes** [test-kitchen/kitchen-azurerm#109]
When using `explicit_resource_group_name` with `destroy_resource_group_contents: true`, any pre-existing tags on the resource group are removed.

```yaml
driver:
  name: azurerm
  explicit_resource_group_name: 'some-group'
  destroy_explicit_resource_group: false
  destroy_resource_group_contents: true
```

If possible, it would be great if these existing resource group tags could be preserved. Perhaps a new flag called `destroy_explicit_resource_group_tags` which defaults to `true` to maintain the current behaviour?
