### ISSUE TITLE
resource_group_tags not applied to resource group

### ISSUE THREAD

**Issue by jmery** [test-kitchen/kitchen-azurerm#115]
# Version:

`kitchen-azurerm (0.14.9)`

# Environment:

Mac OSX 10.14.6 workstation
```
Chef Workstation version: 0.9.42
Chef Infra Client version: 15.3.14
Chef InSpec version: 4.16.0
Chef CLI version: 1.0.16
Test Kitchen version: 2.3.3
Cookstyle version: 5.6.2
```

# Scenario:

Attempting to set tags @ resource group level using the `resource_group_tags` property.  

# Steps to Reproduce:

Use one of the two code snippets below in your kitchen file:
```
platforms:
  - name: centos-7
    driver:
      resource_group_tags:
        X-Contact: <%= ENV['USER'] %>
        X-Application: <%= ENV['X_APPLICATION'] %>
        X-Dept: <%= ENV['X_DEPT'] %>
        X-Customer: "Test-Kitchen"
        X-Project: "Test-Kitchen"
        X-TTL: 4
```
^^^ `driver_config:` produces the same results.

```
---
driver:
  name: azurerm
  azure_resource_group_prefix: kitchen-<%= ENV['USER'] %>-
  resource_group_tags:
    X-Contact: <%= ENV['USER'] %>
    X-Application: <%= ENV['X_APPLICATION'] %>
    X-Dept: <%= ENV['X_DEPT'] %>
    X-Customer: "Test-Kitchen"
    X-Project: "Test-Kitchen"
    X-TTL: 4
```

# Expected Result:

Specified tags should be applied at the resource group level

# Actual Result:

Tags are applied everything inside the resource group, but not to the resource group itself.
