### ISSUE TITLE
VM state is persisted before VM is provisioned

### ISSUE THREAD

**Issue by zanecodes** [test-kitchen/kitchen-azurerm#118]
# Version:

0.14.8

# Environment:

N/A

# Scenario:

Failed Create action due to bad parameters should succeed once parameters are fixed.

# Steps to Reproduce:

Create a `.kitchen.yml` with the following contents, replacing the subscription ID accordingly:
```
---
driver:
  name: azurerm
  subscription_id: '[your subscription ID here]'
  location: 'Central US'
  machine_size: 'Standard_D2_V2'
  password: '<%= ENV['KITCHEN_VM_PASSWORD'] %>'
  image_urn: MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:latest

platforms:
  - name: windows

suites:
  - name: default
```

Run `kitchen create`
Run `env "KITCHEN_VM_PASSWORD=[your password here]" kitchen create`

# Expected Result:

The first `kitchen create` should fail as expected with
```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [{"error"=>{"code"=>"InvalidParameter", "message"=>"Required parameter 'adminPassword' is missing (null).", "target"=>"adminPassword"}}] on default-windows
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

The second should succeed, since the password has now been supplied.

# Actual Result:

Both runs fail with the above error. In this case, it's because the invalid `password` value is [immediately saved to the `state`](https://github.com/test-kitchen/kitchen-azurerm/blob/bd2d7313096689f636d399e894e9a6c68636cf17/lib/kitchen/driver/azurerm.rb#L299), before it is determined to be valid. Then, during the second run, the saved, invalid `password` is used again rather than the new, valid one.
The fix for this should be to only update each `state` value once it has actually been used, to ensure that it is not persisted until it is safe to do so.
