### ISSUE TITLE
kitchen create does not work with azure credentials file.

### ISSUE THREAD

**Issue by Vasu1105** [test-kitchen/kitchen-azurerm#137]
kitchen-azurerm (1.0.0)
[Version of the project installed]

# Environment:
Workstation : Ubuntu 18.04
```
Chef Workstation version: 20.5.38
Chef Infra Client version: 16.1.0
Chef InSpec version: 4.18.114
Chef CLI version: 3.0.1
Test Kitchen version: 2.5.0
Cookstyle version: 6.4.4
```
[Details about the environment such as the Operating System, cookbook details, etc...]

# Scenario:
kitchen create fails when using ~/.azure/credentials file

# Steps to Reproduce:

Created service principle in azure using following command
```az ad sp create-for-rbac --name ServicePrincipalName```

Created the azure credentials files in ~/.azure/credentials as mentioned in the docs
https://github.com/test-kitchen/kitchen-azurerm#configuration

Created .kitchen.yml
```
driver:
  name: azurerm
  subscription_id: 'azure-subscription-id-here'
  location: 'East US 2'
  machine_size: 'Standard_B2ms'

transport:
  ssh_key: ~/.ssh/id_kitchen-azurerm

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-18.04
    driver:
      image_urn: Canonical:UbuntuServer:18.04-LTS:latest
      vm_name: vj-trusty-vm
      vm_tags:
        ostype: linux
        distro: ubuntu

suites:
  - name: default
    run_list:
      - recipe[kitchentesting::default]
    attributes:
```
# Expected Result:
kitchen create should be successful.
[What are you expecting to happen as the consequence of above reproduction steps?]

# Actual Result:
Output after kitchen create

[If you are filing an issue what are the things we need to do in order to repro your problem?]
```
$ kitchen create
-----> Starting Test Kitchen (v2.5.0)
-----> Creating <default-ubuntu-1804>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Must provide tenant id. Use AZURE_TENANT_ID environment variable or set it in credentials file (/home/msys/.azure/credentials)] on default-ubuntu-1804
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

[What actually happens after the reproduction steps?]
