### ISSUE TITLE
Defaulting to Premium SSD Disks for OS & Data Disks

### ISSUE THREAD

**Issue by Dreweasland** [test-kitchen/kitchen-azurerm#192]
Using this config (which is just re-specifying the defaults)
```
use_managed_disks: true
storage_account_type: Standard_LRS
data_disks:
  - lun: 0
  disk_size_gb: 500
```

I'm getting Premium SSD on both the OS disk as well as the data disk as seen here:
![1613503851](https://user-images.githubusercontent.com/2516893/108112092-3b0d6300-705b-11eb-931b-cb3c3533f9dd.png)

I've also tried this without specifying any of the options listed above and the OS disk is still a Premium SSD
