### ISSUE TITLE
InvalidTemplate error on Azure VM creation—"zone" parameter is invalid

### ISSUE THREAD

**Issue by DecoyJoe** [test-kitchen/kitchen-azurerm#232]
# Version:

1.9.0

# Environment:

Windows 10, Cinc Workstation 22.2.807

Driver config:

```
---
driver:
  name: azurerm
  subscription_id: '<id>'
  location: 'West US 2'
  machine_size: 'Standard_DS2_v2'

platforms:
- name: centos-7-7
  driver:
    image_urn: OpenLogic:CentOS:7.7:latest
    vm_name: cookbook-cent7
```

# Scenario:

I've configured my Test Kitchen environment to use the `azurerm` driver as above and am attempting to create the VM with `kitchen create default-centos-7-7`

# Expected Result:

Test Kitchen/azurerm creates the VM in Azure.

# Actual Result:

The creation fails with the following error:

```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [{
  "message": "MsRestAzure::AzureOperationError: InvalidTemplate: Deployment template validation failed: 'The template
  parameters 'zone' in the parameters file are not valid; they are not present in the original template and can
  therefore not be provided at deployment time. The only supported parameters for this template are 'location, vmSize,
  newStorageAccountName, adminUsername, adminPassword, dnsNameForPublicIP, secretUrl, vaultName, vaultResourceGroup,
  existingStorageAccountBlobContainer, imagePublisher, imageOffer, imageSku, imageVersion, osDiskNameSuffix, vmName,
  nicName, publicIPSKU, publicIPAddressType, storageAccountType, systemAssignedIdentity, userAssignedIdentities,
  bootDiagnosticsEnabled'. Please see https://aka.ms/arm-deploy/#parameter-file for usage details.'."
```

This issue is not present if I downgrade to version 1.8.0 of the gem. It appears the issue was introduced in PR [Support vm availability zone #228](https://github.com/test-kitchen/kitchen-azurerm/pull/228).
