### ISSUE TITLE
Resourcegroup could not be found - issue creating resourcegroup because of default name?

### ISSUE THREAD

**Issue by iaingblack** [test-kitchen/kitchen-azurerm#54]
Hi there,

Sorry, but am i doing something wrong here or is there a problem. My .kitchen.yml file is this;

```
---
driver:
  name: azurerm

driver_config:
  subscription_id: '3d5b86a9-f2e5-47ec-86bf-6bea5dea8f06'
  location: 'West Europe'
  machine_size: 'Standard_D1'

provisioner:
  name: chef_zero

platforms:
  - name: windows2012-r2
    driver_config:
      image_urn: MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:latest
    transport:
      name: winrm
suites:
  - name: default
    run_list:
      - recipe[kitchentesting::default]
    attributes:
```

But on running kitchen test i get this error. Below. Interestingly I try and create the resourcegroup name "kitchen-default-windows2012-r2-20170624T080014" manually in my subscription and it will not allow it as it has a trademarked or copyrighted name in it (im guessing windows). 

```
The resource name 'kitchen-default-windows2012-r2-20170624T080014' or a part of the name is a trademarked or reserved word.
```

Sorry if doing something daft, but this seems as simple as it can get, what am I doing wrong? Using an MSDN account which provides around £40 free credit a month if that helps.

```
I, [2017-06-24T09:41:39.979542 #7436]  INFO -- default-windows2012-r2: -----> Cleaning up any prior instances of <default-windows2012-r2>
I, [2017-06-24T09:41:39.982045 #7436]  INFO -- default-windows2012-r2: -----> Destroying <default-windows2012-r2>...
I, [2017-06-24T09:41:39.985046 #7436]  INFO -- default-windows2012-r2: Azure environment: Azure
I, [2017-06-24T09:41:40.042584 #7436]  INFO -- default-windows2012-r2: Destroying Resource Group: kitchen-default-windows2012-r2-20170624T080014
E, [2017-06-24T09:41:40.863132 #7436] ERROR -- default-windows2012-r2: {"error"=>{"code"=>"ResourceGroupNotFound", "message"=>"Resource group 'kitchen-default-windows2012-r2-20170624T080014' could not be found."}}
E, [2017-06-24T09:41:40.866633 #7436] ERROR -- default-windows2012-r2: Destroy failed on instance <default-windows2012-r2>.
E, [2017-06-24T09:41:40.867635 #7436] ERROR -- default-windows2012-r2: ------Exception-------
E, [2017-06-24T09:41:40.867635 #7436] ERROR -- default-windows2012-r2: Class: MsRestAzure::AzureOperationError
E, [2017-06-24T09:41:40.868135 #7436] ERROR -- default-windows2012-r2: Message: {
  "message": "MsRestAzure::AzureOperationError: ResourceGroupNotFound: Resource group 'kitchen-default-windows2012-r2-20170624T080014' could not be found.",
```

**Comment by elconas** [comment]
Can you rename the platform to 'win2012-r2' an give it a try ? 

```
platforms:
  - name: win2012-r2
    driver_config:
      image_urn: MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:latest
    transport:
      name: winrm
```

Alternatively you can rename the resource group:

```
platforms:
  - name: windows2012-r2
    driver_config:
      azure_resource_group_name: kitchen-win2012r2-default
      image_urn: MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:latest
    transport:
      name: winrm
```
