### ISSUE TITLE
Windows Server (2012-r2|2016): The value of parameter windowsConfiguration is invalid.

### ISSUE THREAD

**Issue by alinefr** [test-kitchen/kitchen-azurerm#62]
With the same .kitchen.yml as example 2 on README.
```bash
>>>>>> ------Exception-------                                                                                                                                                                     
>>>>>> Class: Kitchen::ActionFailed                                                                                                                                                               
>>>>>> Message: 1 actions failed.                                                                                                                                                                 
>>>>>>     Failed to complete #create action: [{"error"=>{"code"=>"InvalidParameter", "target"=>"windowsConfiguration", "message"=>"The value of parameter windowsConfiguration is invalid."}}] on
 default-windows2012-r2                                                                                                                                                                           
>>>>>> ----------------------                                                                                                                                                                     
>>>>>> Please see .kitchen/logs/kitchen.log for more details                                                                                                                                      
>>>>>> Also try running `kitchen diagnose --all` for configuration
```
It seems image_urn is been ignored from .kitchen.yml

kitchen diagnose --all shows me:
```bash
driver:                        
      azure_environment: Azure           
      azure_resource_group_name: kitchen-default-windows2012-r2
      boot_diagnostics_enabled: 'true'
      custom_data: ''                                                    
      existing_storage_account_blob_url: ''
      existing_storage_account_container: vhds
      image_id: ''         
      image_url: ''                                                      
      image_urn: Canonical:UbuntuServer:14.04.3-LTS:latest
```
My .kitchen.yml
```yml
---
driver:
  name: azurerm

driver_config:
  subscription_id: ''
  location: 'South Central US'
  machine_size: 'Standard_D1'

provisioner:
  name: chef_zero

platforms:
  - name: windows2012-r2
    drive_config:
      image_urn: MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:latest
      vm_tags: 
        ostype: windows
    transport:
      name: winrm

verifier:
  name: pester

suites:
  - name: default
```
