### ISSUE TITLE
Environmental variables have no effect on drive configs

### ISSUE THREAD

**Issue by rokka-n** [test-kitchen/kitchen-azurerm#63]
Hi,

I was trying to set up an example with env variables, but it's not possible since ~/.azure/credentials is a hardcoded requirement

```
driver:
  name: azurerm

driver_config:
  subscription_id: <%= ENV['VAR_subscription_id'] %>
  tenant_id: <%= ENV['VAR_tenant_id'] %>
  client_id: <%= ENV['VAR_client_id'] %>
  client_secret: <%= ENV['VAR_client_secret'] %>
  location: 'West Europe'
  machine_size: 'Standard_D1'
```

Would it make sense for standard env work as in any kitchen config?

Thanks!
