### ISSUE TITLE
Using template for the VM you're testing?

### ISSUE THREAD

**Issue by jimontheriver** [test-kitchen/kitchen-azurerm#64]
I'm brand new to Chef in general, so there's every chance this me just being oblivious:

Is it possible to use your own template for the VM that is being tested? Alternately (for my immediate problem) how would I add data disks?

The Predeployment template works fine for me, but it also seems to try to always create another VM to use as the one being tested. I don't see how you change the template for that VM. Looking at source, it seems we're locked into using one of the two templates provided. 

I've put the predeployment template under platforms like so:
```
platforms:
  - name: ubuntu-16.04.0
    driver_config:
      pre_deployment_template: mytemplate.json
      pre_deployment_parameters: 
          # snip...
```
I also tried putting it under a root level driver_config at the top of the .kitchen.yml. The template fires in both locations just fine.

The element I need to add is data disks so I can test array creation, but in general I think it is a good idea to support your own template as we don't know what ARM features MS will add tomorrow. Keeping it all DSL is great, but it also slows down how quickly we can bring new features into test.
