### ISSUE TITLE
VM with data disks can't deploy to existing vnet/subnet

### ISSUE THREAD

**Issue by huckj** [test-kitchen/kitchen-azurerm#66]
I am able to successfully create a test-kitchen VM that targets an existing vnet/subnet.  I am also able to successfully create a test-kitchen VM that has data disks attached.  If i try to combine the scenarios and create a VM with data disks in an existing vnet/subnet, test-kitchen fails with the below exception.  It appears that in this combined scenario, the JSON for adding the data disks is being inserted into the "diagnosticsProfile" section.  I've tried both 0.12.1 and 0.12.0.  Any thoughts?

kitchen.yml:

```
platforms:
- name: windows2016
  driver_config:
    image_urn: MicrosoftWindowsServer:WindowsServer:2016-Datacenter:latest
    data_disks:
      - lun: 0
        disk_size_gb: 128
    vnet_id: /subscriptions/<SUBSCRIPTION_GUID>/resourceGroups/<RESOURCE_GROUP>/providers/Microsoft.Network/virtualNetworks/<VNET>
    subnet_id: <SUBNET>
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [409: unexpected token at '{
            "apiVersion": "2017-03-30",
            "type": "Microsoft.Compute/virtualMachines",
            "name": "[variables('vmName')]",
            "location": "[variables('location')]",
            "dependsOn": [
                "[concat('Microsoft.Network/networkInterfaces/', variables('nicName'))]"
            ],
            "properties": {
                "hardwareProfile": {
                    "vmSize": "[variables('vmSize')]"
                },
                "osProfile": {
                    "computername": "[variables('vmName')]",
                    "adminUsername": "[parameters('adminUsername')]",
                    "adminPassword": "[parameters('adminPassword')]"
                },
                "storageProfile": {
                    "imageReference": {
                        "publisher": "[parameters('imagePublisher')]",
                        "offer": "[parameters('imageOffer')]",
                        "sku": "[parameters('imageSku')]",
                        "version": "[parameters('imageVersion')]"
                    },
                    "osDisk": {
                        "name": "osdisk",
                        "createOption": "FromImage"
                    }
                },
                "networkProfile": {
                    "networkInterfaces": [
                        {
                            "id": "[resourceId('Microsoft.Network/networkInterfaces',variables('nicName'))]"
                        }
                    ]
                },
                "diagnosticsProfile": {
                      ,"dataDisks":
                          [{"name":"datadisk0","lun":0,"diskSizeGB":128,"createOption":"Empty"}]
                }
            },
            "tags": {
                "provider": "[variables('provider')]"

            }
        }
    ]
}
'] on default-windows2016-noformat
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
