### ISSUE TITLE
Data_munger error undefined method `rmerge' for #<Array:0x00000000067270f8>

### ISSUE THREAD

**Issue by DanielCCotter** [test-kitchen/kitchen-azurerm#76]
Hello I am receiving the below error, I am new to chef.

```
C:\Windows\system32\cmd.exe /D /S /C "c:\opscode\chefdk\bin\chef.bat exec kitchen verify"
-----> Starting Kitchen (v1.20.0)
c:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/data_munger.rb:369:in `convert_legacy_driver_format_at!': undefined method `rmerge' for #<Array:0x00000000067270f8> (NoMethodError)
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/data_munger.rb:348:in `block in convert_legacy_driver_format!'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/data_munger.rb:347:in `each'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/data_munger.rb:347:in `convert_legacy_driver_format!'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/data_munger.rb:42:in `initialize'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/config.rb:152:in `new'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/config.rb:152:in `data'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/config.rb:131:in `suites'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/config.rb:182:in `filter_instances'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/config.rb:141:in `build_instances'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/config.rb:117:in `instances'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/command.rb:112:in `filtered_instances'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/command.rb:142:in `parse_subcommand'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/command/action.rb:35:in `block in call'
        from c:/opscode/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/command/action.rb:34:in `call'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/cli.rb:52:in `perform'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/cli.rb:193:in `block (2 levels) in <class:CLI>'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/bin/kitchen:13:in `block in <top (required)>'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/errors.rb:171:in `with_friendly_errors'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/bin/kitchen:13:in `<top (required)>'
        from c:/opscode/chefdk/bin/kitchen:262:in `load'
        from c:/opscode/chefdk/bin/kitchen:262:in `<main>'
```

.kitchen.yml
```
---
driver:
  name: azurerm

driver_config:
  location: 'East US'
  machine_size: 'D2s_v3'

transport:
  ssh_key: ~/.ssh/id_kitchen-azurerm

provisioner:
  name: chef_zero

verifier:
  name: inspec  

platforms:
- name: ubuntu-16.04
  driver_config:
  - image_urn: Canonical:UbuntuServer:16.04-LTS:latest
  - vm_name: DCCTestUbuntu
  vm_tags:
  - ostype: linux
  - distro: ubuntu

suites:
  name: default
  run_list:
  - recipe[DCCTest::default]
  inspec_tests:
  - test/integration/default
attributes:
```

**Comment by cheeseplus** [comment]
I think this is mostly formatting issues:

```
---
driver:
  name: azurerm
  location: 'East US'
  machine_size: 'D2s_v3'

transport:
  ssh_key: ~/.ssh/id_kitchen-azurerm

provisioner:
  name: chef_zero

verifier:
  name: inspec  

platforms:
- name: ubuntu-16.04
  driver:
    image_urn: Canonical:UbuntuServer:16.04-LTS:latest # note these are just keys, not array items
    vm_name: DCCTestUbuntu # note these are just keys, not array items
    vm_tags:
      ostype: linux # note these are just keys, not array items
      distro: ubuntu # note these are just keys, not array items

suites:
  name: default
  run_list:
  - recipe[DCCTest::default]
  verifier:
    inspec_tests:
    - test/integration/default
attributes:

**Comment by DanielCCotter** [comment]
Thanks Seth this has moved me along however I now get this error
data_munger.rb:366:in `convert_legacy_driver_format_at!': undefined method `key?' for [:name, "default"]:Array (NoMethodError)

---
driver:
  name: azurerm

driver_config:
  location: 'East US'
  machine_size: 'D2s_v3'

transport:
  ssh_key: ~/.ssh/id_kitchen-azurerm

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
- name: ubuntu-16.04
  driver_config:
   image_urn: Canonical:UbuntuServer:16.04-LTS:latest
   vm_name: DCCTestUbuntu
   vm_tags:
    ostype: linux
    distro: ubuntu

suites:
  name: default
  run_list:
  - recipe[DCCTest::default]
  inspec_tests:
  - test/integration/default
attributes:

**Comment by cheeseplus** [comment]
Looks like I missed the formatting in `suites`:

```
suites:
  - name: default
    run_list:
    - recipe[DCCTest::default]
    verifier:
      inspec_tests:
      - test/integration/default
```

I fixed the snippet above to be correct as well.
