### ISSUE TITLE
Windows 10 kitchen converge: A connection attempt failed because the connected party did not properly respond after a period of time

### ISSUE THREAD

**Issue by dee3sync** [test-kitchen/kitchen-azurerm#89]
Hello, 
I am trying to deploy a test kitchen using windows 10.  If I swap the image_urn to `image_urn: MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:latest` my kitchen converge works fine but if I use the the windows 10 image urn `image_urn: "MicrosoftWindowsDesktop:Windows-10:rs4-pro:latest"` I receive a connection error. Even if I change the urn to reference rs3 or rs2, the same error occurs.

Current versions:
```
Chef Development Kit Version: 3.0.39
chef-client version: 14.1.12
berks version: 7.0.2
kitchen version: 1.21.2
inspec version: 2.2.10
kitchen-azurerm (0.14.1)
```

Error Message:
```
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #converge action: [A connection attempt failed because the connected party did not properly respond after a period
of time, or established connection failed because connected host has failed to respond. - A connection attempt failed because the connected party did
not properly respond after a period of time, or established connection failed because connected host has failed to respond. - connect(2) for "23.99.138.194" port 5985 (23.99.138.194:5985)]
```

Here is my .kitchen.yml (note - the cookbook::recipe listed is not in the supermarket, it is internal)
```
---
driver:
  name: azurerm
  subscription_id: "<%= ENV['subscription'] %>"
  location: 'Central US'
  machine_size: 'Standard_D2_V2'
  username: "<%= ENV['username'] %>"
  password: "<%= ENV['password'] %>"

transport:
  name: winrm
  elevated: true

verifier:
  name: inspec

provisioner:
  name: chef_zero
  deprecations_as_errors: true
  retry_on_exit_code:
    - 20
    - 35
  max_retries: 10
  wait_for_retry: 180
  client_rb:
    exit_status: :enabled

platforms:
  - name: Windows-10
    driver:
      image_urn: "MicrosoftWindowsDesktop:Windows-10:rs4-pro:latest"

suites:
  - name: default
    run_list:
      - recipe[workstation::default]
  ```

**Comment by stuartpreston** [comment]
My guess would be that for some reason the commands to enable WinRM correctly on the Windows Server  give a different response on that Windows 10 image.  Not sure why just yet but I'll try and carve out some time to look into it. 

For reference this is the WinRM configuration script that is encoded and run on the machine: https://github.com/test-kitchen/kitchen-azurerm/blob/master/lib/kitchen/driver/azurerm.rb#L442-L448

And as you can see you could set a `winrm_powershell_script` in your configuration if you find the answer before me :)

**Comment by stuartpreston** [comment]
@dee3sync Did you find out the cause of the problem here?

**Comment by dee3sync** [comment]
@stuartpreston No...I don't understand what you would like me to add in my .kitchen.yml to try to debug this issue.

**Comment by stuartpreston** [comment]
@dee3sync I tried this out today and as suspected, the image used does not have WinRM or the Firewall rule required for this to work for that specific Windows 10 image.  Here's the modification required to your .kitchen.yml:
```
platforms:
  - name: Windows-10
    driver:
      image_urn: "MicrosoftWindowsDesktop:Windows-10:rs4-pro:latest"
      winrm_powershell_script: |-
                               Enable-PSRemoting -SkipNetworkProfileCheck -Force
                               New-NetFirewallRule -DisplayName "Windows Remote Management (HTTP-In)" -Name "Windows Remote Management (HTTP-In)" -Profile Any -LocalPort 5985 -Protocol TCP
```
Please give this a go and see if you get further.
